services:
  app:
    image: janisbe/komornik-gpt:latest
    container_name: komornik-gpt
    ports:
      - "80:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.0.0.194:54322/komornik
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=hasloKOMORNIK
      - SPRING_CONFIG_IMPORT=optional:file:/app/daneDoKont.properties
      - SPRING_SQL_INIT_MODE=never
      - CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:80,http://127.0.0.1,http://localhost:4200
    networks:
      - komornik-network
    volumes:
      - /home/opc/daneDoKont.properties:/app/daneDoKont.properties

networks:
  komornik-network:
    driver: bridge

volumes:
  pgdata:
