global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'komornik-app'
    metrics_path: '/actuator/prometheus'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ 'app:8443' ]
