# Database (prawdziwy serwer)
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

url=https://komornik.site
frontend.url=https://komornik.site
# Importy prod - opcjonalny plik (teraz używamy zmiennych środowiskowych)
spring.config.import=optional:file:/app/daneDoKontProd.properties,classpath:common.properties
# Sesja i bezpiecze?stwo
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.partitioned=true
jwt.cookie.secure=true
jwt.cookie.domain=komornik.site
# SSL
server.port=443
# Logging prod
logging.file.name=/app/logs/app.log
# Monitoring
management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true
