# Baza danych (lokalna)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/komornik}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never
spring.flyway.locations=classpath:db/migration,classpath:db/testdata
# Adresy lokalne
url=http://localhost:8080
frontend.url=http://localhost:4200
# MailDev dla środowiska lokalnego
spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:1025}
spring.mail.username=${SPRING_MAIL_USERNAME:no-reply@komornik.local}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
# Logowanie i debug w trybie lokalnym
logging.level.org.springframework.security=error
logging.level.org.springframework.security.oauth2=error
logging.level.com.janis.komornikgpt.auth=error
# Ciasteczka lokalne (brak wymogu HTTPS)
jwt.cookie.secure=false
