export enum Currency {
  USD = "USD",
  EUR = "EUR",
  PLN = "PLN",
  GBP = "GBP",
  JPY = "JPY",
  CHF = "CHF",
  AUD = "AUD",
  CAD = "CAD",
  CNY = "CNY",
  SEK = "SEK",
  NZD = "NZD",
  MXN = "MXN",
  SGD = "SGD",
  HKD = "HKD",
  NOK = "NOK",
  KRW = "KRW",
  TRY = "TRY",
  RUB = "RUB",
  INR = "INR",
  BRL = "BRL",
  ZAR = "ZAR",
  DKK = "DKK",
  TWD = "TWD",
  THB = "THB",
  MYR = "MYR",
  IDR = "IDR",
  CZK = "CZK",
  HUF = "HUF",
  ILS = "ILS",
  CLP = "CLP",
  PHP = "PHP",
  AED = "AED",
  COP = "COP",
  SAR = "SAR",
  RON = "RON",
  PEN = "PEN",
  VND = "VND",
  PKR = "PKR",
  KZT = "KZT",
  EGP = "EGP"
}

export interface CurrencyInfo {
  code: Currency;
  description: string;
  symbol: string;
}

export const CurrencyDetails: Record<Currency, CurrencyInfo> = {
  [Currency.USD]: {code: Currency.USD, description: "Dolar amerykański", symbol: "$"},
  [Currency.EUR]: {code: Currency.EUR, description: "Euro", symbol: "€"},
  [Currency.PLN]: {code: Currency.PLN, description: "Polski złoty", symbol: "zł"},
  [Currency.GBP]: {code: Currency.GBP, description: "Funt szterling", symbol: "£"},
  [Currency.JPY]: {code: Currency.JPY, description: "Jen japoński", symbol: "¥"},
  [Currency.CHF]: {code: Currency.CHF, description: "Frank szwajcarski", symbol: "CHF"},
  [Currency.AUD]: {code: Currency.AUD, description: "Dolar australijski", symbol: "$"},
  [Currency.CAD]: {code: Currency.CAD, description: "Dolar kanadyjski", symbol: "$"},
  [Currency.CNY]: {code: Currency.CNY, description: "Juan chiński", symbol: "¥"},
  [Currency.SEK]: {code: Currency.SEK, description: "Korona szwedzka", symbol: "kr"},
  [Currency.NZD]: {code: Currency.NZD, description: "Dolar nowozelandzki", symbol: "$"},
  [Currency.MXN]: {code: Currency.MXN, description: "Peso meksykańskie", symbol: "$"},
  [Currency.SGD]: {code: Currency.SGD, description: "Dolar singapurski", symbol: "$"},
  [Currency.HKD]: {code: Currency.HKD, description: "Dolar hongkoński", symbol: "$"},
  [Currency.NOK]: {code: Currency.NOK, description: "Korona norweska", symbol: "kr"},
  [Currency.KRW]: {code: Currency.KRW, description: "Won południowokoreański", symbol: "₩"},
  [Currency.TRY]: {code: Currency.TRY, description: "Lira turecka", symbol: "₺"},
  [Currency.RUB]: {code: Currency.RUB, description: "Rubel rosyjski", symbol: "₽"},
  [Currency.INR]: {code: Currency.INR, description: "Rupia indyjska", symbol: "₹"},
  [Currency.BRL]: {code: Currency.BRL, description: "Real brazylijski", symbol: "R$"},
  [Currency.ZAR]: {code: Currency.ZAR, description: "Rand południowoafrykański", symbol: "R"},
  [Currency.DKK]: {code: Currency.DKK, description: "Korona duńska", symbol: "kr"},
  [Currency.TWD]: {code: Currency.TWD, description: "Nowy dolar tajwański", symbol: "$"},
  [Currency.THB]: {code: Currency.THB, description: "Baht tajski", symbol: "฿"},
  [Currency.MYR]: {code: Currency.MYR, description: "Ringgit malezyjski", symbol: "RM"},
  [Currency.IDR]: {code: Currency.IDR, description: "Rupia indonezyjska", symbol: "Rp"},
  [Currency.CZK]: {code: Currency.CZK, description: "Korona czeska", symbol: "Kč"},
  [Currency.HUF]: {code: Currency.HUF, description: "Forint węgierski", symbol: "Ft"},
  [Currency.ILS]: {code: Currency.ILS, description: "Szekel izraelski", symbol: "₪"},
  [Currency.CLP]: {code: Currency.CLP, description: "Peso chilijskie", symbol: "$"},
  [Currency.PHP]: {code: Currency.PHP, description: "Peso filipińskie", symbol: "₱"},
  [Currency.AED]: {code: Currency.AED, description: "Dirham ZEA", symbol: "د.إ"},
  [Currency.COP]: {code: Currency.COP, description: "Peso kolumbijskie", symbol: "$"},
  [Currency.SAR]: {code: Currency.SAR, description: "Rial saudyjski", symbol: "﷼"},
  [Currency.RON]: {code: Currency.RON, description: "Lej rumuński", symbol: "lei"},
  [Currency.PEN]: {code: Currency.PEN, description: "Sol peruwiański", symbol: "S/"},
  [Currency.VND]: {code: Currency.VND, description: "Dong wietnamski", symbol: "₫"},
  [Currency.PKR]: {code: Currency.PKR, description: "Rupia pakistańska", symbol: "₨"},
  [Currency.KZT]: {code: Currency.KZT, description: "Tenge kazachstańskie", symbol: "₸"},
  [Currency.EGP]: {code: Currency.EGP, description: "Funt egipski", symbol: "£"}
};
